name: CI3

on:
  schedule:
    - cron: "0 * * * *"
    - cron: "1 * * * *"
    - cron: "2 * * * *"
    - cron: "3 * * * *"
    - cron: "4 * * * *"
    - cron: "5 * * * *"
    - cron: "6 * * * *"
    - cron: "7 * * * *"
    - cron: "8 * * * *"
    - cron: "9 * * * *"
    - cron: "10 * * * *"
    - cron: "11 * * * *"
    - cron: "12 * * * *"
    - cron: "13 * * * *"
    - cron: "14 * * * *"
    - cron: "15 * * * *"
    - cron: "16 * * * *"
    - cron: "17 * * * *"
    - cron: "18 * * * *"
    - cron: "19 * * * *"
    - cron: "20 * * * *"
    - cron: "21 * * * *"
    - cron: "22 * * * *"
    - cron: "23 * * * *"
    - cron: "24 * * * *"
    - cron: "25 * * * *"
    - cron: "26 * * * *"
    - cron: "27 * * * *"
    - cron: "28 * * * *"
    - cron: "29 * * * *"
    - cron: "30 * * * *"
    - cron: "31 * * * *"
    - cron: "32 * * * *"
    - cron: "33 * * * *"
    - cron: "34 * * * *"
    - cron: "35 * * * *"
    - cron: "36 * * * *"
    - cron: "37 * * * *"
    - cron: "38 * * * *"
    - cron: "39 * * * *"
    - cron: "40 * * * *"
    - cron: "41 * * * *"
    - cron: "42 * * * *"
    - cron: "43 * * * *"
    - cron: "44 * * * *"
    - cron: "45 * * * *"
    - cron: "46 * * * *"
    - cron: "47 * * * *"
    - cron: "48 * * * *"
    - cron: "49 * * * *"
    - cron: "50 * * * *"
    - cron: "51 * * * *"
    - cron: "52 * * * *"
    - cron: "53 * * * *"
    - cron: "54 * * * *"
    - cron: "55 * * * *"
    - cron: "56 * * * *"
    - cron: "57 * * * *"
    - cron: "58 * * * *"
    - cron: "59 * * * *"
  # 手動実行用の記述
  workflow_dispatch:

jobs:
  Release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create GitHub release note
        run: |
          cat ./release_note.txt > github_release_note.txt
          MESSAGE="${{ github.workflow }} #${{ github.run_number }}"
          URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo -e "\n[${MESSAGE}](${URL})" >> github_release_note.txt
          cat github_release_note.txt

      - name: Test data
        run: |
          dd if=/dev/zero of=dummy.txt bs=1M count=150

      - name: Create GitHub release note
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ github.workflow }} #${{ github.run_number }}"
          tag_name: 'schedule_${{ github.run_id }}'
          draft: true
          body_path: ./github_release_note.txt
          files: |
            ./dummy.txt,
